default_language_version:
  python: python3.11  # Ensure this matches your CI's python-version

repos:
  # Pre-commit hooks for general file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^ffmint-iam/(app|tests)/.*\.py$
      - id: end-of-file-fixer
        files: ^ffmint-iam/(app|tests)/.*\.py$
      - id: check-yaml
        files: ^ffmint-iam/.*\.(yaml|yml)$
      - id: check-json
        files: ^ffmint-iam/.*\.json$

  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^ffmint-iam/(app|tests)/.*\.py$
      - id: ruff-format
        files: ^ffmint-iam/(app|tests)/.*\.py$

  # Black for code formatting
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
        files: ^ffmint-iam/(app|tests)/.*\.py$

  # Pylint for static analysis
  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        additional_dependencies:
          - pytest
          - pylint-pydantic
          - pydantic
          - fastapi
          - sqlalchemy
          - passlib
        files: ^ffmint-iam/(app|tests)/.*\.py$

  # Mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        language_version: python3.11
        files: ^ffmint-iam/(app|tests)/.*\.py$
