[project]
name = "FFMint"
version = "0.1.0"
description = """
FFMint is your ultimate digital platform. It unites portfolios, retail,
service businesses, and publishers (creators, news) in one intuitive app.
Launch custom-branded sites, manage operations, and connect, all
seamlessly.
"""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "asyncpg>=0.30.0",
  "fastapi[standard]>=0.115.12",
  "isort>=6.0.1",
  "passlib[bcrypt]>=1.7.4",
  "psycopg2-binary>=2.9.10",
  "pydantic>=2.11.5",
  "pydantic-extra-types>=2.10.5",
  "pylint>=3.3.7",
  "pytest>=8.4.0",
  "pytest-dotenv>=0.5.2",
  "python-dotenv>=1.1.0",
  "python-jose[cryptography]>=3.5.0",
  "sqlalchemy>=2.0.41",
  "uvicorn>=0.34.3",
]

[tool.uv]
dev-dependencies = [
  "black>=25.1.0",
  "ruff>=0.11.12"
]

[tool.ruff]
# Maximum allowed line length
line-length = 88

# Which codes to select:
#   E: pycodestyle (PEP 8)
#   F: pyflakes
#   I: import-related
#   R: Ruff-specific
#   W: warnings
lint.select = ["E", "F", "I", "R", "W"]

[tool.isort]
# Use a known profile (e.g. "black", "google", "pep8")
profile = "black"

# Match Ruff's max line length
line_length = 88

# Group first-party imports
known_first_party = ["app", "ffmint-iam", "ffm-storage"]

[tool.pylint]
# Disable some message codes you don't want, including E0401 for missing imports
disable = [
  "C0114",  # missing-module-docstring
  "C0115",  # missing-class-docstring
  "C0116",  # missing-function-docstring
  "E0401",  # unable-to-import
]

# Match line length to 88
max-line-length = 88

# Good variable names are lowercase; adjust regex if needed
variable-rgx = "[a-z_][a-z0-9_]{2,30}$"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --showlocals --strict-markers"
testpaths = [
  "tests",
]
pythonpath = ["."]
python_files = "test_*.py"
python_classes = "Test"
python_functions = "test_"
