[project]
name = "FFMint"
version = "0.1.0"
description = "FFMint is your ultimate digital platform. It unites portfolios, retail, service businesses, and publishers (creators, news) in one intuitive app. Launch custom-branded sites, manage operations, and connect, all seamlessly."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydantic-extra-types>=2.10.5",
    "uvicorn>=0.34.3",
]

[tool.uv]
dev-dependencies = [
  "black>=25.1.0",
  "ruff>=0.11.12"
]

[tool.ruff]
line-length = 88
lint.extend-select = ["I","ANN"]  # "I" enables Ruff's isort rules
