name: CI - Lint and Test

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  iam:
    runs-on: ubuntu-latest
    name: IAM Service - Lint & Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        working-directory: ffmint-iam
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        working-directory: ffmint-iam
        run: |
          uv pip install --system -r <(uv pip compile pyproject.toml)
          uv pip install --system flake8 isort pylint pytest

      - name: Lint with flake8
        working-directory: ffmint-iam
        run: flake8 --max-line-length=88 app tests

      - name: Check import order with isort
        working-directory: ffmint-iam
        run: isort --check-only --diff app tests

      - name: Lint with pylint
        working-directory: ffmint-iam
        run: pylint app tests

      - name: Run tests with pytest
        working-directory: ffmint-iam
        run: pytest tests

  # sstorage:
  #   runs-on: ubuntu-latest
  #   name: SStorage Service - Lint & Test

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.10'

  #     - name: Install uv
  #       working-directory: ffmint-sstorage
  #       run: |
  #         curl -Ls https://astral.sh/uv/install.sh | bash
  #         echo "$HOME/.cargo/bin" >> $GITHUB_PATH

  #     - name: Install dependencies with uv
  #       working-directory: ffmint-sstorage
  #       run: |
  #         uv pip install --system -r <(uv pip compile pyproject.toml)
  #         uv pip install --system flake8 isort pylint pytest

  #     - name: Lint with flake8
  #       working-directory: ffmint-sstorage
  #       run: flake8 --max-line-length=88 app tests

  #     - name: Check import order with isort
  #       working-directory: ffmint-sstorage
  #       run: isort --check-only --diff app tests

  #     - name: Lint with pylint
  #       working-directory: ffmint-sstorage
  #       run: pylint app tests

  #     - name: Run tests with pytest
  #       working-directory: ffmint-sstorage
  #       run: pytest tests
