name: CI - Lint and Test

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  iam:
    runs-on: ubuntu-latest
    name: IAM Service – Lint & Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        working-directory: ffmint-iam
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        working-directory: ffmint-iam
        run: |
          uv pip install --system -r <(uv pip compile pyproject.toml)
          uv pip install --system ruff pylint pytest

      - name: Lint with Ruff
        working-directory: ffmint-iam
        run: ruff --line-length=88 .

      - name: Lint with Pylint
        working-directory: ffmint-iam
        run: pylint --max-line-length=88 app tests

      - name: Run tests with pytest
        working-directory: ffmint-iam
        run: pytest tests

  # storage:
  #   runs-on: ubuntu-latest
  #   name: Storage Service – Lint & Test

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.10'

  #     - name: Install uv
  #       working-directory: ffm-storage
  #       run: |
  #         curl -Ls https://astral.sh/uv/install.sh | bash
  #         echo "$HOME/.cargo/bin" >> $GITHUB_PATH

  #     - name: Install dependencies with uv
  #       working-directory: ffm-storage
  #       run: |
  #         uv pip install --system -r <(uv pip compile pyproject.toml)
  #         uv pip install --system ruff pylint pytest

  #     - name: Lint with Ruff
  #       working-directory: ffm-storage
  #       run: ruff --line-length=88 .

  #     - name: Lint with Pylint
  #       working-directory: ffm-storage
  #       run: pylint --max-line-length=88 app tests

  #     - name: Run tests with pytest
  #       working-directory: ffm-storage
  #       run: pytest tests
